
package com.srivastava.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalcWSService", targetNamespace = "http://ws.srivastava.com/", wsdlLocation = "http://localhost:8080/CalcWebService/CalcWS?wsdl")
public class CalcWSService
    extends Service
{

    private final static URL CALCWSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCWSSERVICE_EXCEPTION;
    private final static QName CALCWSSERVICE_QNAME = new QName("http://ws.srivastava.com/", "CalcWSService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/CalcWebService/CalcWS?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCWSSERVICE_WSDL_LOCATION = url;
        CALCWSSERVICE_EXCEPTION = e;
    }

    public CalcWSService() {
        super(__getWsdlLocation(), CALCWSSERVICE_QNAME);
    }

    public CalcWSService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCWSSERVICE_QNAME, features);
    }

    public CalcWSService(URL wsdlLocation) {
        super(wsdlLocation, CALCWSSERVICE_QNAME);
    }

    public CalcWSService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCWSSERVICE_QNAME, features);
    }

    public CalcWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalcWSService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalcWS
     */
    @WebEndpoint(name = "CalcWSPort")
    public CalcWS getCalcWSPort() {
        return super.getPort(new QName("http://ws.srivastava.com/", "CalcWSPort"), CalcWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalcWS
     */
    @WebEndpoint(name = "CalcWSPort")
    public CalcWS getCalcWSPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.srivastava.com/", "CalcWSPort"), CalcWS.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCWSSERVICE_EXCEPTION!= null) {
            throw CALCWSSERVICE_EXCEPTION;
        }
        return CALCWSSERVICE_WSDL_LOCATION;
    }

}
